# Generated by Django 4.1 on 2024-05-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало диапазона/Недоступная дата')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Конец диапазона')),
            ],
            options={
                'verbose_name': 'Диапазон недоступных дат',
                'verbose_name_plural': 'Диапазоны недоступных дат',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonDataAndDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Запись',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, unique=True, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Время записи',
                'verbose_name_plural': 'Время записей',
                'ordering': ['time'],
            },
        ),
        migrations.AddIndex(
            model_name='time',
            index=models.Index(fields=['time'], name='sign_up_tim_time_904f0f_idx'),
        ),
        migrations.AddField(
            model_name='persondataanddate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sign_up.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='persondataanddate',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sign_up.time', verbose_name='Время'),
        ),
    ]
