# Generated by Django 4.1 on 2024-05-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persondataanddate',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='disableddates',
            name='creator_is_human',
            field=models.BooleanField(default=True),
        ),
    ]
