# Generated by Django 4.1 on 2024-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0004_alter_disableddates_creator_is_human'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondataanddate',
            name='payment_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='id платежа предоплаты'),
        ),
    ]
