# Generated by Django 4.1 on 2024-06-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0005_persondataanddate_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_service', models.CharField(max_length=50, verbose_name='Доп. услуга')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Доп. услугу',
                'verbose_name_plural': 'Доп. услуги',
            },
        ),
    ]
