# Generated by Django 4.1 on 2024-06-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0006_additionalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondataanddate',
            name='additional_service',
            field=models.ManyToManyField(blank=True, to='sign_up.additionalservice'),
        ),
    ]
