# Generated by Django 4.1 on 2024-07-20 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sign_up', '0007_persondataanddate_additional_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondataanddate',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='persondataanddate',
            name='additional_service',
            field=models.ManyToManyField(blank=True, to='sign_up.additionalservice', verbose_name='Дополнительные услуги'),
        ),
    ]
