# Generated by Django 4.1 on 2024-08-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0008_persondataanddate_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persondataanddate',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
