# Generated by Django 5.0.3 on 2024-04-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateForSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceForHtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('time_to_comp', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('prepayment', models.IntegerField()),
                ('filming_work', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/images/for_service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesForSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='signup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='service',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='time',
        ),
        migrations.AddField(
            model_name='signup',
            name='_datetime',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.dateforsignup'),
        ),
        migrations.AddField(
            model_name='dateforsignup',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.servicesforsignup'),
        ),
    ]
