# Generated by Django 5.0.3 on 2024-04-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_dateforsignup_serviceforhtml_servicesforsignup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceforhtml',
            name='image',
            field=models.ImageField(upload_to='images/for_service/'),
        ),
        migrations.AlterField(
            model_name='servicesforsignup',
            name='service',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
