# Generated by Django 5.0.3 on 2024-04-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_serviceforhtml_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дату записи',
                'verbose_name_plural': 'Даты записей',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DisabledDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало диапазона/Недоступная дата')),
                ('finish_date', models.DateField(null=True, verbose_name='Конец диапазона')),
            ],
            options={
                'verbose_name': 'Диапазон недоступных дат',
                'verbose_name_plural': 'Диапазоны недоступных дат',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, unique=True, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.RemoveField(
            model_name='dateforsignup',
            name='service',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='_datetime',
        ),
        migrations.AlterModelOptions(
            name='serviceforhtml',
            options={'ordering': ['id'], 'verbose_name': 'Услугу, отображаемую на сайте', 'verbose_name_plural': 'Услуги, отображаемые на сайте'},
        ),
        migrations.AlterField(
            model_name='serviceforhtml',
            name='filming_work',
            field=models.IntegerField(verbose_name='Снятие чужой работы'),
        ),
        migrations.AlterField(
            model_name='serviceforhtml',
            name='image',
            field=models.ImageField(upload_to='images/for_service/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceforhtml',
            name='prepayment',
            field=models.IntegerField(verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='serviceforhtml',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='serviceforhtml',
            name='service',
            field=models.CharField(max_length=50, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='serviceforhtml',
            name='time_to_comp',
            field=models.CharField(max_length=50, verbose_name='Время выполнения'),
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Время записи',
                'verbose_name_plural': 'Время записей',
                'ordering': ['time'],
                'indexes': [models.Index(fields=['time'], name='main_page_t_time_a08570_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_page.date', verbose_name='Дата')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_page.service', verbose_name='Услуга')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_page.time', verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.AddField(
            model_name='date',
            name='time',
            field=models.ManyToManyField(to='main_page.time', verbose_name='Время'),
        ),
        migrations.DeleteModel(
            name='ServicesForSignUp',
        ),
        migrations.DeleteModel(
            name='DateForSignUp',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['date'], name='main_page_d_date_ec2005_idx'),
        ),
    ]
