# Generated by Django 5.0.3 on 2024-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_date_disableddates_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServiceForHtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, verbose_name='Услуга')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Доп. услугу',
                'verbose_name_plural': 'Доп. услуги, отображаемые на сайте',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='disableddates',
            options={'ordering': ['start_date'], 'verbose_name': 'Диапазон недоступных дат', 'verbose_name_plural': 'Диапазоны недоступных дат'},
        ),
        migrations.AlterField(
            model_name='disableddates',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец диапазона'),
        ),
    ]
