# Generated by Django 4.1 on 2024-05-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_additionalserviceforhtml_alter_disableddates_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceforhtml',
            name='image',
            field=models.ImageField(upload_to='main_page/images/for_service/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='serviceforhtml',
            name='time_to_comp',
            field=models.CharField(max_length=50, verbose_name='Время выполнения в часах'),
        ),
    ]
