# Generated by Django 4.1 on 2024-06-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_serviceforhtml_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='time',
        ),
        migrations.DeleteModel(
            name='DisabledDates',
        ),
        migrations.RemoveField(
            model_name='personname',
            name='date',
        ),
        migrations.RemoveField(
            model_name='personname',
            name='service',
        ),
        migrations.RemoveField(
            model_name='personname',
            name='time',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='PersonName',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
